### ISSUE TITLE
v1.2.0分页出现问题

### ISSUE THREAD

**Issue by yanggengzhen123** [wangjainxi/nb-fe-pdf#14]
你好，v.1.2.0分页出现问题，可以留个联系方式吗，方便沟通，另外项目在启动时遇到的坑比较多
![image](https://github.com/wangjainxi/nb-fe-pdf/assets/55992838/64c80364-606d-4a67-a96c-890ceae882e4)

**Comment by wangjainxi** [comment]
用 "version": "1.2.1"版本
