### ISSUE TITLE
最新版本代码的 demo 表格错乱

### ISSUE THREAD

**Issue by Jenkyn** [wangjainxi/nb-fe-pdf#15]
**错乱表格如下：**
<img width="987" alt="image" src="https://github.com/wangjainxi/nb-fe-pdf/assets/8737772/18f9b476-0a9e-44de-95ab-1ab741929ee9">

[同步下载报告~2023_10_8 18_16_04.pdf](https://github.com/wangjainxi/nb-fe-pdf/files/12844574/2023_10_8.18_16_04.pdf)

**复现步骤**
- clone 最新代码（commit id: a0bfe5a4b7af57100ddf49d358aa5af2132c5e89） 
- 修改package.json里的puppeteer 版本，升级到21.3.8（默认版本不支持arm64）
- 按照文档安装依赖，运行demo，访问 http://localhost:8080/syncPage 下载pdf

**设备信息：**
  型号名称：	MacBook Pro
  型号标识符：	MacBookPro18,3
  型号：	MKGP3CH/A
  芯片：	Apple M1 Pro
  系统版本：	macOS 13.5.2 (22G91)
  内核版本：	Darwin 22.6.0
  启动宗卷：	Macintosh HD

**Comment by wangjainxi** [comment]
用版本 "version": "1.2.1",
